-- 게시판 테이블 생성 ( 테이블 명 : HBOARD )
CREATE TABLE HBOARD
(
    IDX	        NUMBER(5,0)         PRIMARY KEY,
    MENU_ID 	CHAR(6 BYTE)        NOT NULL,
    TITLE	    VARCHAR2(100 BYTE)  NOT NULL,
    CONT	    VARCHAR2(4000 BYTE),
    WRITER	    VARCHAR2(10)        NOT NULL,
    CONSTRAINT  FK_WRITER FOREIGN KEY(WRITER)
    REFERENCES  CLIENTINFO(CID),
    REGDATE	    DATE                DEFAULT SYSDATE,
    READCOUNT	NUMBER(5,0),
    BNUM	    NUMBER(5,0),
    LVL	        NUMBER(5,0),
    STEP	    NUMBER(5,0),
    NREF	    NUMBER(5,0),
    DELNUM	    NUMBER(1,0)
);

COMMIT;