insert into clientinfo values ('Admin', 1234, 19800505, '관리자', 'Admin@naver.com', 'H3', sysdate);
insert into clientinfo values ('Sky', 1234, 19901010, '스카이', 'Sky@naver.com', 'H1', sysdate);
insert into clientinfo values ('Sea', 1234, 19901010, '바다', 'sea@naver.com', 'H2', sysdate);
EXEC PKG_HBOARD.PROC_BOARD_INSERT('MENU01', '제목테스트2', '내용테스트2', 'Sea', 0, 0, 0, 0);
EXEC PKG_HBOARD.PROC_BOARD_PAGINGLIST( MENU01, 1, 5);

commit;

SELECT COUNT(CID) FROM CLIENTINFO;

SELECT ROW_NUMBER() OVER( ORDER BY  CID ASC ) AS RN, CID, CPWD, CBIRTH, CNAME, CEMAIL, CRESULT, TO_CHAR(RESDAY,'YYYY-MM-DD') RESDAY
FROM CLIENTINFO;

VAR V_CID VARCHAR2;
VAR V_CPWD VARCHAR2;
CALL PKG_MEMBER.PROC_MEMBER_LOGIN ('Sky', 1234, :V_CID , :V_CPWD);
PRINT :V_CID;
PRINT :V_CPWD;

SELECT CID, CPWD FROM CLIENTINFO WHERE CID ='Sky' AND CPWD = 1234;

SELECT CNAME FROM CLIENTINFO C join HBOARD H ON C.CID = H.WRITER AND H.WRITER = 'Sky';

VAR V_CUR REFCURSOR;
CALL PKG_MEMBER.PROC_MEMBER_MEMBERLIST (:V_CUR);
PRINT :V_CUR;

SELECT ROW_NUMBER() OVER( ORDER BY  NREF DESC, STEP ASC ) AS RN, IDX, MENU_ID, TITLE, WRITER, TO_CHAR(REGDATE,'YYYY-MM-DD HH24:MI:SS') REGDATE, CNAME, READCOUNT, BNUM, LVL, STEP, NREF, DELNUM
FROM HBOARD H JOIN CLIENTINFO C
ON H.WRITER = C.CID;

UPDATE HBOARD
SET TITLE = '테스트수정', CONT = '테스트입니다를 수정'
WHERE IDX = 3;
rollback;

CREATE TABLE HBOARD_COMMENT 
(
	COMMENT_IDX  NUMBER(5,0)  PRIMARY KEY
	COMMENT_HBOARD  NUMBER(5,0)  NOT NULL
	CONSTRAINT FK_COMMENT FOREIGN KEY( COMMENT_HBOARD) REFERENCES HBOARD(IDX)
	COMMENT_WRITER  VARCHAR2(10) NOT NULL
	COMMENT_REGDATE  DATE  DEFAULT  SYSDATE
	COMMENT_CONT  VARCHAR2(1000)  NOT NULL
	COMMENT_BNUM NUMBER(5,0)
	COMMENT_LVL NUMBER(5,0)
	COMMENT_STEP NUMBER(5,0)
	COMMENT_NREF NUMBER(5,0)
	COMMENT_DELNUM NUMBER(1,0)
);

alter table HBOARD_COMMENT add comment_bnum number(5,0);
alter table HBOARD_COMMENT add comment_LVL number(5,0);
alter table HBOARD_COMMENT add comment_STEP number(5,0);
alter table HBOARD_COMMENT add comment_NREF number(5,0);
alter table HBOARD_COMMENT add comment_DELNUM number(5,0);
alter table HBOARD_COMMENT drop column COMMENT_PARENT;

          SELECT
            ROW_NUMBER() OVER( ORDER BY  NREF DESC, STEP ASC ) AS RN,
            LEVEL, COMMENT_IDX, COMMENT_HBOARD,
            COMMENT_WRITER, TO_CHAR(COMMENT_REGDATE,'YYYY-MM-DD HH24:MI:SS') COMMENT_REGDATE, 
            COMMENT_PARENT, COMMENT_CONT
          FROM
            HBOARD_COMMENT HC JOIN HBOARD H
          ON
            HC.COMMENT_HBOARD = H.IDX
            START WITH COMMENT_PARENT = 0
            CONNECT BY PRIOR COMMENT_IDX = COMMENT_PARENT;
            
            
exec PKG_HBOARD.PROC_BOARD_COMMENTINSERT(1,'Sea', '테스트입니다', 0, 0, 0, 0);

VAR V_CUR Refcursor;
exec PKG_HBOARD.PROC_BOARD_COMMENTPAGINGLIST( 1, 1, 10, :V_CUR);
PRINT :V_CUR;

         Select
            ROW_NUMBER() OVER( ORDER BY  NREF DESC, STEP ASC ) AS RN,
            COMMENT_IDX, COMMENT_HBOARD,
            COMMENT_WRITER, TO_CHAR(COMMENT_REGDATE,'YYYY-MM-DD HH24:MI:SS') COMMENT_REGDATE, 
            COMMENT_CONT, COMMENT_BNUM, COMMENT_LVL, COMMENT_STEP, COMMENT_NREF, COMMENT_DELNUM
          FROM
            HBOARD_COMMENT HC JOIN HBOARD H
          ON
            HC.COMMENT_HBOARD = H.IDX
          And
            Comment_Hboard =2;

    DELETE FROM HBOARD
    WHERE IDX = 12;
    
    UPDATE
    (
    SELECT HC.COMMENT_IDX, HC.COMMENT_CONT, HC.COMMENT_WRITER
    FROM HBOARD H, HBOARD_COMMENT HC
    WHERE H.IDX = HC.COMMENT_HBOARD
    AND H.IDX = IN_COMMENT_HBOARD
    )
    SET COMMENT_CONT = '수정함'
    WHERE COMMENT_IDX = IN_COMMENT_IDX;
    
    
SELECT 
COMMENT_IDX, COMMENT_HBOARD, COMMENT_WRITER,
TO_CHAR(COMMENT_REGDATE, 'YYYY-MM-DD HH24:MI:SS') COMMENT_REGDATE,
COMMENT_CONT, COMMENT_BNUM, COMMENT_LVL, COMMENT_STEP, COMMENT_NREF, COMMENT_DELNUM
FROM HBOARD_COMMENT HC JOIN HBOARD H
ON HC.COMMENT_HBOARD = H.IDX
AND COMMENT_HBOARD = IN_IDX;



          SELECT
            ROW_NUMBER() OVER( ORDER BY  CID ASC ) AS RN,
            CID, CPWD,
            CBIRTH, CNAME, CEMAIL, CRESULT,
            TRUNC(RESDAY,'DD')
          FROM
            CLIENTINFO; 

SELECT TRUNC(RESDAY,'DD') RESDAY FROM clientinfo;    

insert into clientinfo values ('Admin8', 1234, 19800505, '관리자', 'Admin8@naver.com', 'H3', sysdate);
commit;

    SELECT   COMMENT_NREF,   COMMENT_LVL,   COMMENT_STEP
     FROM    HBOARD_COMMENT
     WHERE   COMMENT_IDX  =  39;

SELECT * FROM  HBOARD_COMMENT HC
WHERE NOT   EXISTS (
SELECT  *  FROM HBOARD_COMMENT
WHERE  COMMENT_NREF =  10
AND   COMMENT_LVL  =  1
AND   COMMENT_STEP =  1
     ) AND  COMMENT_IDX   =  40;

VAR V_CUR REFCURSOR;
call PKG_HAIR.PROC_CINFO_LOGIN(:V_CUR);
PRINT :V_CUR;

    SELECT CID, CPWD
    FROM CLIENTINFO
    WHERE CID = 'Sky'
    AND   CPWD = '1234';
    
        SELECT CID, CPWD
    FROM CLIENTINFO;