-- CMD 이용해서 오라클 계정 만들기
-- 1) sqlplus /nolog
-- 2) conn sys/1234 as sysdba
-- 3) create user hair identified 1234;
-- 4) grant connect, resource to hair;
---------------------------------------------

SELECT *  FROM all_tables WHERE table_name = 'HBOARD';

-- 회원정보 테이블 생성 ( 테이블 명 : CLIENTINFO )
CREATE TABLE CLIENTINFO
(
    CID     VARCHAR2(10)    PRIMARY KEY, 

    CPWD    VARCHAR2(10)    NOT NULL,

    CBIRTH  NUMBER(8)       NOT NULL,

    CNAME   VARCHAR2(10)    NOT NULL,
 
    CEMAIL  VARCHAR2(20)    UNIQUE,

    CRESULT VARCHAR2(30)    NULL,
    CONSTRAINT  FK_HAIR_ID FOREIGN KEY(CRESULT)
    REFERENCES  HAIRS(HAIR_ID),
    RESDAY  DATE            
);

Alter Table CLIENTINFO add     CONSTRAINT  FK_HAIR_ID FOREIGN KEY(CRESULT) REFERENCES  HAIRS(HAIR_ID);

COMMIT;

-- 게시판 테이블 생성 ( 테이블 명 : HBOARD )
CREATE TABLE HBOARD
(
    IDX	        NUMBER(5,0)         PRIMARY KEY,
    MENU_ID 	CHAR(6 BYTE)        NOT NULL,
    TITLE	    VARCHAR2(100 BYTE)  NOT NULL,
    CONT	    VARCHAR2(4000 BYTE),
    WRITER	    VARCHAR2(10)        NOT NULL,
    CONSTRAINT  FK_WRITER FOREIGN KEY(WRITER)
    REFERENCES  CLIENTINFO(CID),
    REGDATE	    DATE                DEFAULT SYSDATE,
    READCOUNT	NUMBER(5,0),
    BNUM	    NUMBER(5,0),
    LVL	        NUMBER(5,0),
    STEP	    NUMBER(5,0),
    NREF	    NUMBER(5,0),
    DELNUM	    NUMBER(1,0)
);

 SELECT NVL(MAX(IDX), 0) + 1
FROM HBOARD;

COMMIT;

DROP TABLE FACESHAPE;

CREATE TABLE FACESHAPE
(
    FACE_NUM        NUMBER(2,0)         PRIMARY KEY NOT NULL,
    FACE_NAME       VARCHAR2(20)        NOT NULL
);

INSERT INTO FACESHAPE VALUES ('1', 'OVAL');
INSERT INTO FACESHAPE VALUES ('2', 'SQUARE');
INSERT INTO FACESHAPE VALUES ('3', 'OBLONG');
INSERT INTO FACESHAPE VALUES ('4', 'TRIANGULAR');
INSERT INTO FACESHAPE VALUES ('5', 'ROUND');
INSERT INTO FACESHAPE VALUES ('6', 'DIAMOND');
INSERT INTO FACESHAPE VALUES ('7', 'HEART');

CREATE TABLE HAIRS
(
    HAIR_ID     VARCHAR2(6)         PRIMARY KEY NOT NULL,
    HAIR_NAME   VARCHAR2(30)        NOT NULL,
    FACE_NUM    NUMBER(2,0),
    CONSTRAINT  FK_FACE_NUM FOREIGN KEY(FACE_NUM)
    REFERENCES  FACESHAPE(FACE_NUM)
);

INSERT INTO HAIRS VALUES ('H1', 'Pushed_Back_Long','1');
INSERT INTO HAIRS VALUES ('H2', 'Side_Parted_Short','1');
INSERT INTO HAIRS VALUES ('H3', 'Undercut','1');
INSERT INTO HAIRS VALUES ('H4', 'Fringe_Up','1');

INSERT INTO HAIRS VALUES ('H5', 'Crew_aka_Buzz_Cut','2');
INSERT INTO HAIRS VALUES ('H6', 'Undercut','2');
INSERT INTO HAIRS VALUES ('H7', 'Faux_Hawk','2');
INSERT INTO HAIRS VALUES ('H8', 'Slicked_Back_Side_Part','2');

INSERT INTO HAIRS VALUES ('H9', 'Side_Parted','3');
INSERT INTO HAIRS VALUES ('H10', 'Buzz_Cut','3');
INSERT INTO HAIRS VALUES ('H11', 'Fringe_Up','3');
INSERT INTO HAIRS VALUES ('H12', 'Side_Fringe','3');

INSERT INTO HAIRS VALUES ('H13', 'Fringe_Up','4');
INSERT INTO HAIRS VALUES ('H14', 'Side_Fringe','4');
INSERT INTO HAIRS VALUES ('H15', 'Side_Parted','4');

INSERT INTO HAIRS VALUES ('H16', 'Faux_Hawk_With_Shorter_Sides','5');
INSERT INTO HAIRS VALUES ('H17', 'Side_Fringe','5');
INSERT INTO HAIRS VALUES ('H18', 'Undercut','5');
INSERT INTO HAIRS VALUES ('H19', 'Quiff','5');

INSERT INTO HAIRS VALUES ('H20', 'Quiff','6');
INSERT INTO HAIRS VALUES ('H21', 'Long_Hair_Pushed_Back','6');
INSERT INTO HAIRS VALUES ('H22', 'Faux_Hawk','6');
INSERT INTO HAIRS VALUES ('H23', 'Side_Fringe','6');

INSERT INTO HAIRS VALUES ('H24', 'Long_Fringes','7');
INSERT INTO HAIRS VALUES ('H25', 'Side_Parted_Long','7');
INSERT INTO HAIRS VALUES ('H26', 'Pushed_Back','7');
INSERT INTO HAIRS VALUES ('H27', 'Unercut','7');

COMMIT;
