-- 게시판 테이블 생성 ( 테이블 명 : HBOARD_COMMENT )
CREATE TABLE HBOARD_COMMENT
(
	COMMENT_IDX  NUMBER(5,0)  PRIMARY KEY,
	COMMENT_HBOARD  NUMBER(5,0)  NOT NULL,
	CONSTRAINT FK_COMMENT FOREIGN KEY( COMMENT_HBOARD) REFERENCES HBOARD(IDX),
	COMMENT_WRITER  VARCHAR2(10) NOT NULL,
	COMMENT_REGDATE  DATE  DEFAULT  SYSDATE,
	COMMENT_CONT  VARCHAR2(1000)  NOT NULL,
	COMMENT_BNUM NUMBER(5,0),
	COMMENT_LVL NUMBER(5,0),
	COMMENT_STEP NUMBER(5,0),
	COMMENT_NREF NUMBER(5,0),
	COMMENT_DELNUM NUMBER(1,0)

);

COMMIT;