create or replace PACKAGE PKG_CLIENTINFO AS 

--회원가입
  PROCEDURE PROC_CINFO_INSERT(
        IN_CID      IN  VARCHAR2,
        IN_CPWD     IN  VARCHAR2,
        IN_CNAME    IN  VARCHAR2,
        IN_CBIRTH   IN  NUMBER,  
        IN_CEMAIL   IN  VARCHAR2     
        );

-- 로그인  
  PROCEDURE PROC_CINFO_LOGIN ( IN_CID IN VARCHAR2, IN_CPWD IN VARCHAR2, O_CID OUT VARCHAR2, O_CPWD OUT VARCHAR2);

-- 이름 가져오기
  PROCEDURE PROC_CINFO_GET_NAME ( IN_CID IN VARCHAR2, O_CNAME OUT VARCHAR2 );

-- 아이디 찾기
  PROCEDURE PROC_CINFO_SEARCH_ID ( IN_CNAME IN VARCHAR2, IN_CEMAIL IN VARCHAR2, O_CID OUT VARCHAR2 );
  
-- 비밀번호 찾기
  PROCEDURE PROC_CINFO_TEMP_PWD ( IN_CID IN VARCHAR2, IN_CNAME IN VARCHAR2, IN_CEMAIL IN VARCHAR2 );

-- 아이디 가져오기
  PROCEDURE PROC_CINFO_GET_ID( IN_CID IN VARCHAR2, O_CID OUT VARCHAR2 );

-- 비밀번호 가져오기
  PROCEDURE PROC_CINFO_GET_PWD( IN_CID IN VARCHAR2, O_CPWD OUT VARCHAR2 );
  
END PKG_CLIENTINFO;