create or replace PACKAGE PKG_HBOARD AS 

  PROCEDURE PROC_BOARD_INSERT( IN_MENU_ID IN VARCHAR2, IN_TITLE IN VARCHAR2, IN_CONT IN VARCHAR2, IN_WRITER  IN VARCHAR2, IN_BNUM IN NUMBER, IN_LVL IN NUMBER, IN_STEP IN NUMBER, IN_NREF IN NUMBER);
  PROCEDURE PROC_BOARD_PAGINGLIST( IN_MENU_ID IN VARCHAR2, IN_NOWPAGE IN NUMBER, IN_PAGECOUNT IN NUMBER, OUT_TOTALCOUNT OUT NUMBER, O_CUR OUT SYS_REFCURSOR);
  PROCEDURE PROC_BOARD_VIEW( IN_IDX IN NUMBER, O_CUR  OUT SYS_REFCURSOR);
  PROCEDURE PROC_BOARD_UPDATE( IN_IDX IN NUMBER, IN_TITLE IN VARCHAR2, IN_CONT IN VARCHAR2);
  PROCEDURE PROC_BOARD_DELETE( IN_IDX IN NUMBER );
  PROCEDURE PROC_BOARD_BOARDCOMMENTVIEW( IN_IDX IN NUMBER, O_CUR OUT SYS_REFCURSOR);
  PROCEDURE PROC_BOARD_COMMENTVIEW( IN_COMMENT_IDX IN NUMBER, O_CUR OUT SYS_REFCURSOR);
  PROCEDURE PROC_BOARD_COMMENTINSERT( IN_COMMENT_HBOARD IN NUMBER, IN_COMMENT_WRITER IN VARCHAR2, IN_COMMENT_CONT IN VARCHAR2, IN_COMMENT_BNUM IN NUMBER, IN_COMMENT_LVL IN NUMBER, IN_COMMENT_STEP IN NUMBER, IN_COMMENT_NREF IN NUMBER);
  PROCEDURE PROC_BOARD_COMMENTUPDATE( IN_COMMENT_IDX IN NUMBER, IN_COMMENT_HBOARD IN NUMBER, IN_COMMENT_CONT IN VARCHAR2);
  PROCEDURE PROC_BOARD_COMMENTDELETE( IN_COMMENT_IDX IN NUMBER );
  PROCEDURE PROC_BOARD_COMMENTPAGINGLIST( IN_IDX IN VARCHAR2, IN_NOWPAGE IN NUMBER, IN_PAGECOUNT IN NUMBER, OUT_TOTALCOUNT OUT NUMBER, O_CUR OUT SYS_REFCURSOR);
END PKG_HBOARD;