create or replace PACKAGE BODY PKG_MEMBER AS

  PROCEDURE PROC_MEMBER_PAGINGLIST( IN_NOWPAGE IN NUMBER, IN_PAGECOUNT IN NUMBER, OUT_TOTALCOUNT OUT NUMBER, O_CUR OUT SYS_REFCURSOR) AS
    V_STARTNUM NUMBER(8);
    V_ENDNUM NUMBER(8);
  BEGIN

    -- 페이징을 위한 전체자료수
    SELECT    COUNT(CID)
    INTO     OUT_TOTALCOUNT
    FROM     CLIENTINFO;
    
    -- 가져올 자료의 시작번호, 끝번호
    V_STARTNUM  :=  (IN_NOWPAGE-1) * IN_PAGECOUNT + 1;
    V_ENDNUM    :=  IN_NOWPAGE * IN_PAGECOUNT; 
     
    IF( V_ENDNUM >= OUT_TOTALCOUNT  )  THEN
      V_ENDNUM := OUT_TOTALCOUNT; 
    END IF;
    
    -- DATA 가져오기
    OPEN O_CUR FOR
      SELECT  * FROM
        (
          SELECT
            ROW_NUMBER() OVER( ORDER BY  CID ASC ) AS RN,
            CID, CPWD,
            CBIRTH, CNAME, CEMAIL, CRESULT,
            RESDAY
          FROM
            CLIENTINFO       
       ) T
       WHERE T.RN   BETWEEN   V_STARTNUM  AND   V_ENDNUM;
    
  END PROC_MEMBER_PAGINGLIST;

  PROCEDURE PROC_MEMBER_LOGIN ( IN_CID IN VARCHAR2, IN_CPWD IN VARCHAR2, O_CID OUT VARCHAR2, O_CPWD OUT VARCHAR2) AS
  V_CID VARCHAR2(10);
  V_CPWD VARCHAR2(10);
  BEGIN
    
    SELECT CID, CPWD
    INTO O_CID, O_CPWD
    FROM CLIENTINFO
    WHERE CID = IN_CID AND CPWD = IN_CPWD;
    
  END PROC_MEMBER_LOGIN;

  PROCEDURE PROC_MEMBER_MEMBERLIST ( O_CUR OUT SYS_REFCURSOR ) AS
  BEGIN
        OPEN O_CUR FOR
        SELECT CID, CPWD, CBIRTH, CNAME, CEMAIL, CRESULT, RESDAY
        FROM CLIENTINFO
        ORDER BY CID ASC;
        
  END PROC_MEMBER_MEMBERLIST;

END PKG_MEMBER;