create or replace PACKAGE BODY PKG_CLIENTINFO AS

-- 회원가입
  PROCEDURE PROC_CINFO_INSERT(
        IN_CID      IN  VARCHAR2,
        IN_CPWD     IN  VARCHAR2,
        IN_CNAME    IN  VARCHAR2,
        IN_CBIRTH   IN  NUMBER,
        IN_CEMAIL   IN  VARCHAR2
        ) AS
  BEGIN
    
    INSERT INTO CLIENTINFO ( CID, CPWD, CNAME, CBIRTH, CEMAIL ) 
    VALUES (IN_CID, IN_CPWD, IN_CNAME, IN_CBIRTH, IN_CEMAIL);
    COMMIT;
    
    
  END PROC_CINFO_INSERT;

-- 로그인
  PROCEDURE PROC_CINFO_LOGIN ( IN_CID IN VARCHAR2, IN_CPWD IN VARCHAR2, O_CID OUT VARCHAR2, O_CPWD OUT VARCHAR2) AS
    V_CID VARCHAR2(10);
    V_CPWD VARCHAR2(10);
  BEGIN
    
    SELECT CID, CPWD
    INTO   O_CID, O_CPWD
    FROM   CLIENTINFO
    WHERE  CID = IN_CID AND CPWD = IN_CPWD;
    
  END PROC_CINFO_LOGIN;

-- 이름 가져오기
  PROCEDURE PROC_CINFO_GET_NAME ( IN_CID IN VARCHAR2, O_CNAME OUT VARCHAR2 ) AS
  BEGIN
    
    SELECT  CNAME
      INTO  O_CNAME
      FROM  CLIENTINFO
     WHERE  CID = IN_CID;
     
  END PROC_CINFO_GET_NAME;

 -- 아이디 찾기
  PROCEDURE PROC_CINFO_SEARCH_ID ( IN_CNAME IN VARCHAR2, IN_CEMAIL IN VARCHAR2, O_CID OUT VARCHAR2 ) AS
  BEGIN
    SELECT  CID
      INTO  O_CID
      FROM  CLIENTINFO
     WHERE  CNAME   = IN_CNAME
      AND   CEMAIL = IN_CEMAIL;
  END PROC_CINFO_SEARCH_ID;

-- 비밀번호 찾기 - 임시비밀번호 '1234'로 발급
  PROCEDURE PROC_CINFO_TEMP_PWD ( IN_CID IN VARCHAR2, IN_CNAME IN VARCHAR2, IN_CEMAIL IN VARCHAR2 ) AS
  BEGIN
    UPDATE  CLIENTINFO
       SET  CPWD = '1234'
     WHERE  CID    = IN_CID
       AND  CNAME  = IN_CNAME
       AND  CEMAIL = IN_CEMAIL;
  END PROC_CINFO_TEMP_PWD;

-- 아이디 가져오기
  PROCEDURE PROC_CINFO_GET_ID( IN_CID IN VARCHAR2, O_CID OUT VARCHAR2 ) AS
  BEGIN
    SELECT  CID
      INTO  O_CID
      FROM  CLIENTINFO
     WHERE  CID = IN_CID;
  END PROC_CINFO_GET_ID;

-- 비밀번호 가져오기
  PROCEDURE PROC_CINFO_GET_PWD( IN_CID IN VARCHAR2, O_CPWD OUT VARCHAR2 ) AS
  BEGIN
    SELECT  CPWD
      INTO  O_CPWD
      FROM  CLIENTINFO
     WHERE  CID = IN_CID; 
  END PROC_CINFO_GET_PWD;

END PKG_CLIENTINFO;