create or replace PACKAGE PKG_MEMBER AS 

  PROCEDURE PROC_MEMBER_PAGINGLIST( IN_NOWPAGE IN NUMBER, IN_PAGECOUNT IN NUMBER, OUT_TOTALCOUNT OUT NUMBER, O_CUR OUT SYS_REFCURSOR);
  PROCEDURE PROC_MEMBER_MEMBERLIST ( O_CUR OUT SYS_REFCURSOR );
  PROCEDURE PROC_MEMBER_LOGIN ( IN_CID IN VARCHAR2, IN_CPWD IN VARCHAR2, O_CID OUT VARCHAR2, O_CPWD OUT VARCHAR2);

END PKG_MEMBER;